### ISSUE TITLE
Reviewpad stop functioning without any error when the checks configuration is incorrect

### ISSUE THREAD

**Issue by fmallet** [reviewpad/reviewpad#1005]
## How to reproduce

Add the following Reviewpad configuration to a repo:

```yaml
workflows:
  - name: foo
    run:
      - $addLabel("foo")

checks:
  - gitConflict: 
```

Reviewpad execution seems to never be triggered and so there is no available error message to understand what happens. 

## Expected behavior

We expect either Reviewpad to fail with a meaningful error message available in the details page, or to simply ignore the incorrect configuration.
