### ISSUE TITLE
Built-in addAssignees fails if the parameter total is not provided

### ISSUE THREAD

**Issue by ferreiratiago** [reviewpad/reviewpad#1045]
## Describe the bug

According to the [documentation](https://docs.reviewpad.com/guides/built-ins/#addassignees) the built-in `addAssignees` takes the optional parameter `total`. However, if this parameter is not provided the built-in fails with the following error:
```
type inference failed: mismatch in arg types on addAssignees
```

## How to reproduce

1. Create a workflow on the `reviewpad.yml` as follow:
```yml
workflows:
  - name: assign-author
    run:
       - $addAssignees([$getAuthor()])
```
2. Open a pull request to trigger the workflow defined
3. You will see that Reviewpad will fail the error `type inference failed: mismatch in arg types on addAssignees`.

## Expected behavior

The parameter `total` should not be required.
