### ISSUE TITLE
Optional parameters on the renamed built-ins stop working

### ISSUE THREAD

**Issue by ferreiratiago** [reviewpad/reviewpad#1046]
## Describe the bug

After the rename of some of the built-ins (e.g. `assignAssignees` to `addAssignees`) the optional parameters stop working.

The reason is that the [transform](https://github.com/reviewpad/reviewpad/blob/main/engine/transform.go) was not updated along with the function renaming.

## How to reproduce

1. Create a workflow on the `reviewpad.yml` as follow:
```yml
workflows:
  - name: assign-author
    run:
       - $addAssignees([$getAuthor()])
```
2. Open a pull request to trigger the workflow defined
3. You will see that Reviewpad will fail the error `type inference failed: mismatch in arg types on addAssignees`.

## Expected behavior

The optional parameters should work for both the old and new names.
