### ISSUE TITLE
Add label property to checks

### ISSUE THREAD

**Issue by ferreiratiago** [reviewpad/reviewpad#1057]
## Description

The check should include the property `label`, which should allow the user to add the label name to be applied for that particular issue.

Here's an example of a configuration:
```yml
checks:
  stale:
    parameters:
      max-idle-days: 30
    label: stale
    activation: on
```
