### ISSUE TITLE
built-in: length

### ISSUE THREAD

**Issue by marcelosousa** [reviewpad/reviewpad#159]
**Is your feature request related to a problem? Please describe.**
For certain workflows, we need to get the length of a particular array.

For example, we need to support the following rule:
```yml
  - name: has-at-least-one-reviewer
    kind: patch
    description: Has more than one reviewer
    spec: '$length($reviewers) > 1'
```

**Describe the solution you'd like**
To support the above use case, we need to a new built-in utility function `$length`.

Documentation at: https://github.com/reviewpad/docs/pull/11
