### ISSUE TITLE
Distribute review workload between developers

### ISSUE THREAD

**Issue by ferreiratiago** [reviewpad/reviewpad#164]
**Is your feature request related to a problem? Please describe.**
Right now whenever a reviewer assignment is performed reviewpad has no intelligence to it, meaning that on a group of X people it can happen that the reviewers are unevenly distributed.

For instance, on the following `reviewpad.yml` configuration it can happen that `marcelo` gets 80% of the code reviews and `tiago` gets the remaining 20%.

```
api-version: reviewpad.com/v3.x

groups:
  - name: owners
    description: Group of owners
    kind: developers
    spec: '["marcelosousa", "ferreiratiago"]'

rules:
  - name: tautology
    kind: patch
    description: always true
    spec: 'true'

workflows:
  - name: always-assign-reviewer
    description: Add label with size of the pull request
    always-run: true
    if:
      - rule: tautology
        extra-actions:
          - $assignReviewer($group("owners"), 1)
```

Reviewpad should be able to be a bit smart about reviewer assignment to pull requests.

**Describe the solution you'd like**
A possible solution could be to fetch all reviewers from all open pull requests from github and order the reviewers from the least busy.

The calculation of `busy` should be smart and count not only the total amount of pull requests but also the total amount of files (or even the total amount of lines) - an efficient and good strategy should be proposed here.

Maybe even look at the user's github status in order to understand if the user has any busy or vacation status.

**Describe alternatives you've considered**
_none_

**Additional context**
Please also take into consideration the following built-ins:
* [$team](https://docs.reviewpad.com/docs/aladino-builtins#team)
* [$organization](https://docs.reviewpad.com/docs/aladino-builtins#organization-1)
