### ISSUE TITLE
feat: $addToProject built-in

### ISSUE THREAD

**Issue by marcelosousa** [reviewpad/reviewpad#184]
**Is your feature request related to a problem? Please describe.**
One use case that we have is that we want to automatically add a pull request to a given project when the pull request doesn't have an associated issue.

We would like to support the following configuration:
```
api-version: reviewpad.com/v3.x

mode: silent
edition: professional

rules:
  - name: does-not-have-issues
    kind: patch
    description: has associated issue
    spec: '!$hasLinkedIssues()'

 - name: add-to-project
    description: Add to project pull requests without linked issues
    if:
      - rule: does-not-have-issues
    then:
      - '$addToProject("Reviewpad")'
```

**Describe the solution you'd like**
A new built-in function `$addToProject(...)`.

At this stage, it's unclear how we can identify the project is a user friendly way.
