### ISSUE TITLE
Allow custom configuration of built-in actions

### ISSUE THREAD

**Issue by marcelosousa** [reviewpad/reviewpad#199]
Allowing customisation of built-ins actions is useful.

Here's a use case where we want to prevent reviewer assignment for pull requests that are in draft.

Three possible solutions:

```
api-version: reviewpad.com/v3.x

# edition can be team (open-source built-ins) or professional (all available built-ins)
edition: professional

# mode can be either silent (no explanation) or verbose
mode: verbose

# rules specify conditions on pull requests
rules:
  - name: is-draft
    spec: '$isDraft()'

# SOLUTION 1: As a configuration
# configuration of actions
# by default, all actions are enabled
# in this section, we configure when a particular action is disabled
configuration:
  - name: disable-reviewer-assignment
    # if actions had kinds, we could simply put kinds here
    on-actions:
      - '$assignReviewer'
      - '$assignRandomReviewer'
    disabled-if:
      - rule: is-draft

# SOLUTION 2: As a built-in
# workflows specifies a list of workflows; it is a list because the order of 
# execution matters.
workflows:
  - name: reviewer-assignment
    always-run: true
    if:
      - rule: is-draft
    then:
      - '$disableReviewerAssignment()'

# SOLUTION 3: As a general built-in
# workflows specifies a list of workflows; it is a list because the order of 
# execution matters.
workflows:
  - name: reviewer-assignment
    always-run: true
    if:
      - rule: is-draft
    then:
      - '$disableActions(["..."])'
```
