### ISSUE TITLE
Allow for rule specification to be inlined

### ISSUE THREAD

**Issue by marcelosousa** [reviewpad/reviewpad#220]
I'm tired of the verbosity of configurations.

For example:

```
rules:
  - name: is-draft
    spec: '$isDraft()'


workflows:
  - name: reviewer-assignment
    always-run: true
    if:
      - rule: is-draft
    then:
      - ...
```

Should simply be:

```
workflows:
  - name: reviewer-assignment
    always-run: true
    if:
      - '$isDraft()'
    then:
      - ...
```
