### ISSUE TITLE
Introduce pipelines

### ISSUE THREAD

**Issue by marcelosousa** [reviewpad/reviewpad#231]
**Is your feature request related to a problem? Please describe.**

For certain use cases, the initial of workflows as a basic `if X then Y` is not appropriated. 

One example of this is when we want to enforce a pull request to be reviewed first by person X and only when person X approves, then a review is requested to person Y.

At the moment, to model such case, we could do it with the following workflow:

```yml
rules:
  - name: initial-condition
    spec: '....'

  - name: person-X-approved
    spec: '$reviewerStatus("X") == "APPROVED"'

workflows:
  - name: sequential-reviewer
    description: Ask for sequential reviewers
    if:
      - rule: initial-condition
        extra-actions:
          - '$assignReviewer(["X"])'
      - rule: person-X-approved
        extra-actions:
          - '$assignReviewer(["Y"])'  
```

Lets consider when a pull request where the initial-condition is true so that we can go through this review workflow. As soon as `$assignReviewer(["X"])` is executed, we want to be in a state where we are waiting for "X" approval.

When that happens, both the initial-condition and person-X-approved will be true. In this case, the executed program will:

```yml
$assignReviewer(["X"])
$assignReviewer(["Y"])
```

whereas our intention is to just execute `$assignReviewer(["Y"])`.

**Describe the solution you'd like**

At first, I thought we could add a new built-in: `$sequentialReviewers([["X"], ["Y]], "APPROVED")` which receives a sequence of reviewer lists and advances to the next element of the sequence if everyone in the current list has "APPROVED". However, this solution seems very brittle, i.e. what if the user wants to specify a more complicated review process?

Therefore, I propose an extension of the current YML specification to support the concept of 'pipeline'.
```yaml
pipelines:
  - name: STRING
    trigger: [STRING | RULE] # optional
    stages:
      - actions:
           - ALADINO_ACTION_1
           - ALADINO_ACTION_2
        until: [STRING | RULE] # optional
       ...
      - actions:
           - ALADINO_ACTION_1
           - ALADINO_ACTION_2
        until: [STRING | RULE] # optional

```

A pipeline is running iff the trigger is the empty or its evaluation is true.

When a pipeline is running, only one of the stages will be executed.

This stage will be the first where its until clause is empty or its evaluation is true.

Going back to our use case of the sequence of reviewers, we could now specify it with a pipeline:

```yaml
pipelines:
  - name: sequential-reviewer
    trigger: initial-condition
    stages:
      - actions:
           - '$assignReviewer(["X"])'
        until: person-X-approved
      - actions:
           - '$assignReviewer(["Y"])'
```
