### ISSUE TITLE
Stale pull request / issue

### ISSUE THREAD

**Issue by marcelosousa** [reviewpad/reviewpad#241]
A stale pull request / issue is one which does not have activity for X time duration.

Using the cron job in the github action, we should have a specification which allows to put a comment after X time duration of a pull request / issue without activity and after Y time duration to be able to close it.

For users that use https://github.com/actions/stale, they should be able to quickly switch to this configuration.

Some tentative configurations:

```yml

workflows:
  - name: add-label-with-size
    always-run: true
    if:
      - '$lastEventAt() > 7 days ago'
        extra-actions:
          - '$info("This pull request is stale")'
          - '$addLabel("stale")'
      - '$lastEventAt() > 15 days ago'
        extra-actions:
           - '$close("Closing for inactivity")'
```
