### ISSUE TITLE
Allow to add extra actions on inline rules

### ISSUE THREAD

**Issue by ferreiratiago** [reviewpad/reviewpad#267]
**Is your feature request related to a problem? Please describe.**
Right now inline rules are allowed with the following syntax:

```yml
workflows:
  - name: size-small
    if:
      - "$size < 3"   # inline rule
    then:
      - $addLabel("small")
  
  - name: size-medium # inline rule
    if: 
      - "$size >= 3 && $size < 5"
    then:
      - $addLabel("medium")
  
  - name: size-large  # inline rule
    if:
      - "$size > 5"
    then:
      - $addLabel("large")
```

Although this solution works fine we want it to work with `extra-actions`.

**Describe the solution you'd like**
We should be able to also define an inline rule with `rule` and add `extra-actions`.

Therefore the following workflow `size` should be allowed:
```yml
workflows:
  - name: size
    if:
      - rule: "$size < 3"               # inline rule
        extra-actions:
          - $addLabel("small")
      - rule: "$size >= 3 && $size < 5" # inline rule
        extra-actions:
          - $addLabel("medium")
      - rule: "$size > 5"               # inline rule
        extra-actions:
          - $addLabel("large")
```
