### ISSUE TITLE
removeLabel() with multiple labels inside

### ISSUE THREAD

**Issue by schmelto** [reviewpad/reviewpad#333]
It would be nice to have a `removeLabels("label1", "label2", ...)` function.

current solution:
```yml
workflows:
  - name: label-pull-request-with-size
    if:
      - rule: $size() <= 9
        extra-actions:
          - $addLabel("size/XS")
          - $removeLabel("size/S")
          - $removeLabel("size/M")
          - $removeLabel("size/L")
          - $removeLabel("size/XL")
          - $removeLabel("size/XXL")
```

what I would like to do:

```yml
workflows:
  - name: label-pull-request-with-size
    if:
      - rule: $size() <= 9
        extra-actions:
          - $addLabel("size/XS")
          - $removeLabels("size/S", "size/M", ...)
```

or is there another way if the PR gets updated and a new rule will add a new size label to remove the old labels?
