### ISSUE TITLE
filter, any, all built-ins

### ISSUE THREAD

**Issue by marcelosousa** [reviewpad/reviewpad#348]
Add the $filter built-in which receives two arguments:

Argument 1. A list of elements
Argument 2. A lambda function that receives an element and returns a boolean

Returns a list of elements where the function is true for elements

```yml
rule:
  name: check-reviewers
  description: Check that at least two people from the security team are reviewers
  spec: $len($filter($reviewers(), ($dev => $isElementOf($dev, $team("security")))) > 1
```

Once we have the function filter, we should add the built-ins `any` and `all`:

$any and $all takes the same arguments are filter and return a boolean.

$any(LIST, FUNCTION) := $len($filter(LIST, FUNCTION)) > 0 
$all(LIST, FUNCTION)  := $len($filter(LIST, FUNCTION)) == $len(LIST)
