### ISSUE TITLE
`$elemContains()` built-in

### ISSUE THREAD

**Issue by shay2025** [reviewpad/reviewpad#349]
**Is your feature request related to a problem? Please describe.**
It would be nice to have a built-in that upon receiving a keyword and a list of strings, checks for each element of the list if it contains the keyword.

This built-in can have a different name from the one in the title if found appropriate.

**Describe the solution you'd like**
The built-in could could have the following signature:
```
elemContains:: (string, string[]) -> boolean
```

**Describe alternatives you've considered**
None

**Additional context**
Some examples that could use this built-in in a `reviewpad.yml`:
```
rules:
  - name: hasShipItComment
    kind: patch
    description: Verifies if any of the comment body of the pull request contains "ship it"
    spec: $elemContains("ship it", $comments())
```
```
rules:
  - name: skipCIOnCommitMention
    kind: patch
    description: Verifies if any of the commit messages of the pull request contains "skip-ci"
    spec: $elemContains("skip-ci", $commits())
```
