### ISSUE TITLE
`$addToMilestone()` built-in

### ISSUE THREAD

**Issue by shay2025** [reviewpad/reviewpad#350]
**Is your feature request related to a problem? Please describe.**
It would be nice to have an automated way of adding issues/pull requests to a specific milestone.

**Describe the solution you'd like**
Create a built-in `$addToMilestone()` adds the issue/pull request into the given milestone.

If the milestone doesn't exist:
1. warn that the given milestone doesn't exist;
2. create the milestone;
3. add the given issue/pull request to the milestone.

If the issue/pull request already is in the milestone, no action taken.

If the issue/pull request belongs to another milestone, warn about this and add it to the given milestone.

**Describe alternatives you've considered**
None

**Additional context**
An example of usage in a `reviewpad.yml`:
```
workflows:
  - name: add-to-next-release-milestone
    on:
      - issue
      - pull_request
    description: Add to the next release milestone if the issue/pull request has the related label
    if:
      - rule: '$isElementOf("v1.1.3", $labels())'
    then:
      - $addToMilestone("v1.1.3")
```
