### ISSUE TITLE
`./reviewpad-cli check` not working properly for pipelines

### ISSUE THREAD

**Issue by shay2025** [reviewpad/reviewpad#377]
**Describe the bug**
When`./reviewpad-cli check` cmd is run against a `reviewpad.yml` configuration file that has pipelines, although the execution finishes with no errors announced, it returns `Pipelines: []`.

**To Reproduce**
1. Create a `reviewpad.yml` configuration file with, for example, this configuration:
```
api-version: reviewpad.com/v3.x

pipelines:
  - name: security-changes
    trigger: '$hasFilePattern("services/db/migrations/**")'
    stages:
      - actions:
          - '$assignReviewer(["john"])'
        until: $reviewerStatus("john") == "APPROVED"
      - actions:
          - '$assignTeamReviewer(["security"])'
```
2. Run the command `./reviewpad-cli check -f [REVIEWPAD_FILE]`

**Expected behavior**
The field `Pipelines` should be filled correctly.
