### ISSUE TITLE
Automatic review built-in

### ISSUE THREAD

**Issue by shay2025** [reviewpad/reviewpad#384]
It would come in handy a built-in that can perform an automatic review according to a set of rules.
This built-in could have the following signature:
```
$review(review_type, review_message)
``` 
Where `review_type` can only have one of the following string values:
- APPROVE
- REQUEST_CHANGES
- COMMENT

And the `review_message` parameter is the message to write as a comment.

Some use cases:
```yaml
rules:
   - name: code-changes-without-tests
     kind: patch
     description: Changes to src and not to test files
     spec: $hasFilePattern("src/**") && !$hasFilePattern("*_test.go")

workflows:
   - name: request-changes-to-tests
     if:
       - rule: code-changes-without-tests
     then:
       - $review("REQUEST_CHANGES", "Please update the associated tests.")
```
```yaml
workflows:
   - name: automatic-approval-for-dependabot-pull-requests
     if:
       - rule: $author() == "dependabot[bot]"
     then:
       - $review("APPROVE", "Thank you dependabot 🎊")
```
