### ISSUE TITLE
Automatic merged branch deletion built-in

### ISSUE THREAD

**Issue by shay2025** [reviewpad/reviewpad#385]
On GitHub we can set for a repository to delete a head branch once a pull request is merged. However, we may only want this to happen only on certain cases.

It might come in handy to have a built-in `$deleteHeadBranch()` that deletes the head branch.

Use case:
```yaml
workflows:
  - name: delete-head-branch-after-merge
    description: Merge and delete head branch if patch only contains changes to files with extension .md
    if:
      - rule: '$hasFileExtensions([".md"])'
    then:
      - '$merge()'
      - '$deleteHeadBranch()'

```
