### ISSUE TITLE
hasRequiredApprovals built-in

### ISSUE THREAD

**Issue by shay2025** [reviewpad/reviewpad#406]
**Is your feature request related to a problem? Please describe.**
In GitHub, we can set a specific number of required approving reviews to all pull requests in a repository.
However, it would be useful to have a way of specifying more the required approvals depending on the scenario.

**Describe the solution you'd like**
Develop a built-in `hasRequiredApprovals` that given a X number of required approving reviews and a list of specific users, it checked if X of those users had given approving reviews to the pull request.

**Additional context**
```
hasRequiredApprovals:: (Int, []String) => Boolean
```
Use Case:
```
api-version: reviewpad.com/v3.x

rules:
  - name: changes-critical-code
    kind: patch
    description: Changes to critical code
    spec: '$hasAnnotation("critical")'

workflows:
  - name: has-required-approvals
    if:
      - '$hasRequiredApprovals(2, $team("core"))'
    then:
      - '$fail("Blocking the merge")'
```
