### ISSUE TITLE
pullRequestCountBy builtin requires state

### ISSUE THREAD

**Issue by ferreiratiago** [reviewpad/reviewpad#434]
**Describe the bug**
According to reviewpad documentation, the builtin `pullRequestCountBy` has two parameters. The first one is set as required but the second is set as optional.

However, if the second parameter is not provided an error is returned:

```
Error: type inference failed: mismatch in arg types on pullRequestCountBy
```

**To Reproduce**
1. Navigate to reviewpad [playground](https://reviewpad.com/playground)
2. Paste into the editor the following configuration:

```yaml
api-version: reviewpad.com/v3.x

workflows:
  - name: welcome-user
    if:
      - rule: $pullRequestCountBy($author()) == 1
    then:
      # $commentOnce() comments on the pull request once
      # For more details see https://docs.reviewpad.com/guides/built-ins/#commentonce
      - $commentOnce("Thank you for your first contribution.")

      # An alternative is to comment with the pull request author's name
      # - $commentOnce($sprintf("Thank you @%s for your first contribution!", [$author()]))
```

3. Click in the button `RUN`.
4. The following error should appear.

```
> Error: type inference failed: mismatch in arg types on pullRequestCountBy
```

**Expected behavior**
The parameter `state` should be optional and no error should happen if not provided.
