### ISSUE TITLE
Add golangci-lint on task file

### ISSUE THREAD

**Issue by ferreiratiago** [reviewpad/reviewpad#487]
**Is your feature request related to a problem? Please describe.**
We should run a Go linter in order to guarantee some consistency and catch some problems.

**Describe the solution you'd like**
1. Add the task `lint` to `Taskfile`

```yml
lint:
  summary: |
    Runs the linter
    If error try `brew install golangci-lint`
  cmds:
    - golangci-lint run
```

2. Add that task to the list of actions when running `task check`.

3. Run the new `task lint` and fix the issues.
