### ISSUE TITLE
Builtin isLinkedToProject does not work for pull requests

### ISSUE THREAD

**Issue by ferreiratiago** [reviewpad/reviewpad#492]
**Describe the bug**
Currently, it's described that [isLinkedToProject](https://docs.reviewpad.com/guides/built-ins/#islinkedtoproject) works for pull requests but that's not correct.

The reason lies on the [graphql query](https://github.com/reviewpad/reviewpad/blob/main/codehost/github/issues.go#L23) being done, which on works for issues.

**To Reproduce**
1. Create a `reviewpad.yml` file as add the following configuration:
```yml
api-version: reviewpad.com/v3.x

workflows:
  - name: test-isLinkedToProject
    always-run: true
    on:
      - issue
    if:
      - rule: $isLinkedToProject("public")
        extra-actions:
          - $comment("hello")
```
2. Run the app/action with the configuration above against a pull request X
3. You will get the error `Could not resolve to an Issue with the number of X.`

[Here's an example of a failing github app run.](https://github.com/ferreiratiago/paddy/pull/62/checks?check_run_id=9826988646)

**Expected behavior**
The builtin `isLinkedToProject` should work for both issues and pull requests.

**Screenshots**
![Screen Shot 2022-12-01 at 8 45 56 PM](https://user-images.githubusercontent.com/3806676/205156106-1c21ac78-4717-4fb4-b0aa-b473ef10bea3.png)
