### ISSUE TITLE
Merge action should by default be enabled only for open pull requests

### ISSUE THREAD

**Issue by marcelosousa** [reviewpad/reviewpad#525]
**Is your feature request related to a problem? Please describe.**
As soon as we run Reviewpad on closed pull requests, it is possible that workflows conditions for the merge to continue to be valid. This can lead to unwanted behaviours where developers:
1. Try to merge multiple times the same PR;
2. Close pull requests and then add a comment (or change some PR metadata) and trigger the auto-merge workflow.

**Describe the solution you'd like**
By default, the merge built-in should only be enabled if the pull request is open.

**Describe alternatives you've considered**
Do nothing and assume that users will always protect the merge action, e.g:
```yaml
workflos:
    - name: auto-merge-pull-requests
      always-run: true
      if:
          - $state() == "open"
      then:
          - $merge()
```

**Additional context**
A closed pull request can have the following properties:
```yml
        "mergeable": true,
        "mergeable_state": "clean",
```

This means that we can have the workflow:

```yml
    - name: auto-merge-pull-requests
      always-run: true
      if:
          - '!$isMerged() && $description() != ""'
      then:
          - $merge()
```

Consider the following sequence of actions:
1. Open a pull request with empty description
3. Close the pull request
4. Edit the description to be non-empty

It is possible that this pull request will be a state that is mergeable at which point the merge action will run and it will merge the pull request even if it was not possible to do this from the UI without reopening the pull request.
