### ISSUE TITLE
If not all rules from extended file are used then reviewpad github action fails to execute

### ISSUE THREAD

**Issue by tiithansen** [reviewpad/reviewpad#531]
**Describe the bug**
If not all rules from extended file are used then reviewpad github action fails to execute.

common.yml
```
api-version: reviewpad.com/v3.x

labels:
  only-doc-changes:
    color: 8bc34a

rules:
  - name: not-used
    spec: 1 == 1
  - name: only-doc-changes
    spec: $hasFileExtensions([".md", ".MD"])
```

executed.yml
```
api-version: reviewpad.com/v3.x

extends:
  - https://...../common.yml

workflows:
  - name: Check if only doc changes
    if:
      - rule: only-doc-changes
    then:
      - $addLabel("only-doc-changes")
```

**Expected behavior**
Should not fail to add labels in this exact case.
