### ISSUE TITLE
Use label key in $addLabel and $removeLabel built-in

### ISSUE THREAD

**Issue by marcelosousa** [reviewpad/reviewpad#69]
**Is your feature request related to a problem? Please describe.**
Consider the following specification:

```yml
labels:
  major-release:
    name: 'release:major :arrow_up::hash::hash:'
    description: 'Release the changes as a major'
    color: 'BC304A'

rules:
  - name: is-major-release
    kind: patch
    description: Is major release
    spec: '$startsWith($head(), "major/")'

workflows:
  - name: enforce-branch-naming
     description: Enforce branch naming
     always-run: true
     if:
       - rule: head-branch-is-major
         extra-actions:
           - '$addLabel("major-release")'
```

Here in the action `addLabel`, instead of adding the GH label "major-release" we would like to add the name associated with this label in the labels map. This is much nicer than to specify: `$addLabel("release:major :arrow_up::hash::hash:")`

**Describe the solution you'd like**
We should first check in the action if the argument is a key in the labels and if so, retrieve the name associated with it. If no one name is associated with it, we simply use the argument as the name of the label.

**Describe alternatives you've considered**
None.

**Additional context**
Related to #39
