### ISSUE TITLE
Eager evaluation of workflows

### ISSUE THREAD

**Issue by marcelosousa** [reviewpad/reviewpad#695]
**Is your feature request related to a problem? Please describe.**
At the moment, Reviewpad runs in two phases:

1. Synthesise an Aladino program from the reviewpad.yml evaluation
2. Run the Aladino program

In the first phase, except the creation of the GitHub labels, there is no other `side effect` of the evaluation of Reviewpad.

In the second phase, we perform operations over GitHub.

By design, this means that given the file:

```
api-version: reviewpad.com/v3.x

workflows:
    - name: add-label
      always-run: true
      if:
          - rule: $fileCount() == 1
      then:
          - $addLabel("test")

    - name: react-to-test-label
      always-run: true
      if:
          - rule: $hasLabel("test")
      then:
          - $addLabel("final)
```

Assuming that Reviewpad is executed when a PR is open with a single file modified the Phase 1. will generate the program that only contains the instruction `$addLabel("test")`. 

It is the responsibility of the executor of Reviewpad to react again when the label is added so that it will also add the second label "final".

**Describe the solution you'd like**
On a single execution of Reviewpad on the event open PR with a single modified file, it is expected that Reviewpad will add both labels to the PR.

This is a big change on the Reviewpad engine since we will have to fuse both phases.

The documentation on the [semantics](https://docs.reviewpad.com/guides/semantics) will also have to be updated accordingly. 

Technically, we should investigate the lazy or eager could be an evaluation mode - I suspect that it does require a new evaluator if we want to keep both.
