### ISSUE TITLE
Define built-in hasAnyCheckRunCompleted

### ISSUE THREAD

**Issue by ferreiratiago** [reviewpad/reviewpad#732]
## Description

We need to be able to check if a pull request has a check run completed with the provided check run conclusion for the current pull request head.

### Motivation

This built-in will allow us to act when a provided check run happens. For instance,

```yml
pipelines:
  - name: merge
    trigger: $state() == "open"
    stages:
      - actions:
          - $review("REQUEST_CHANGES", "Pull request checks are failing. Please fix them.")
        until: $hasAnyCheckRunCompleted([], "failure")
```

In this case, we are able to request changes when there's any check run completed with `failure`.

## Proposed solution

Define the built-in `hasAnyCheckRunCompleted` that verifies if there is any check run completed for the current pull request head.

### Parameters

| Parameter | Type | Description |
| --- | --- | --- |
| `check_runs_to_ignore` (optional) | []string | List of checks to be disregarded. By default is `[]` |
| `check_conclusions ` (optional) | []string | List of the final conclusions of the check. By default is `[]` |

### Return value

Type | Description
-- | --
boolean | `true` if there is at least one check completed with one of the provided check conclusions. `false` otherwise. |

### Example
`$hasAnyCheckRunCompleted(["reviewpad"], ["failure", "action_required"])`

## Alternatives considered

The built-in `$haveAllChecksRunCompleted()` is great to validate all checks but it fails to look for a single output.
