### ISSUE TITLE
Update built-in assignAssignees

### ISSUE THREAD

**Issue by ferreiratiago** [reviewpad/reviewpad#733]
### WHY

When the input parameter of the `$assignAssignees(...)` built-in is a group, there is no way to assign the Pull Request to a limited number of persons. We need to be able to assign a limited number of assignees from the provided list.

### Motivation

This change will allow us to select a set of assignees from a group.

```yml
groups:
  - name: owners
    spec: '["maria", "john"]'

workflows:
  - name: assign
    always-run: true
    if:
      - rule: '!$isDraft()'
        extra-actions:
          - $assignAssignees($group("owners"), 1)
```

In this case, we are able to assign the pull request to only 1 user from the group `owners`.

## Proposed solution

Add a new parameter called `total` with the total number of users to assign the pull request to.

### Update parameters

| Parameter | Type | Description |
| --- | --- | --- |
| assignees | []string | The list of GitHub logins to assign the pull request / issue to. |
| total (optional) | int | The total number of users to assign to. By default, it assigns to all users in the provided list. | 

### Example
`$assignAssignees($group("owners"), 1)`
