### ISSUE TITLE
Pipelines are running on issues

### ISSUE THREAD

**Issue by ferreiratiago** [reviewpad/reviewpad#734]
## Describe the bug

Currently, [`pipelines`](https://docs.reviewpad.com/guides/syntax#pipeline) are running on issues, which shouldn't be possible.

## How to reproduce

1. Create a `reviewpad.yml` with a `pipeline`
2. Inside that `pipeline` using built-ins that are only available for on `pull_request`. Example

```yml
api-version: reviewpad.com/v3.x

workflows:
  - name: add-label
    always-run: true
    on:
      - issue
    if:
      - rule: $state() == "open"
        extra-actions:
          - $addLabel("hello")

pipelines:
  - name: assignment
    trigger: $state() == "open"
    stages:
      - actions: $assignReviewer(["john"])
```

4. Create an issue
5. You will see that Reviewpad won't add the label `hello`.

Reviewpad will fail with the error `eval: unsupported kind issues`.  This is due to the fact that `assignReviewer` is not available for pull requests.

## Expected behavior

`pipelines` should only run on pull requests.

**Comment by shay2025** [comment]
The given example should be:
```
api-version: reviewpad.com/v3.x

workflows:
  - name: add-label
    always-run: true
    on:
      - issue
    if:
      - rule: $state() == "open"
        extra-actions:
          - $addLabel("hello")

pipelines:
  - name: assignment
    trigger: $state() == "open"
    stages:
      - actions: 
        - $assignReviewer(["john"])
```
Or else, we get the error:
```
Error: error running reviewpad team edition. Details yaml: unmarshal errors:
  line 17: cannot unmarshal !!str `$assign...` into []string
```
