### ISSUE TITLE
Built-in hasRequiredApprovals ignores latest reviews

### ISSUE THREAD

**Issue by ferreiratiago** [reviewpad/reviewpad#754]
## Describe the bug

Currently, the built-in [`hasRequiredApprovals`](https://docs.reviewpad.com/guides/built-ins/#hasrequiredapprovals) returns `true` if one of the required approvals has an approval review regardless of the latest review status.

For instance, if we use the built-in `hasRequiredApprovals(1, ["peter"])` and `peter` does the reviews:
- R1: `Approval`
- R2: `Request changes`

The built-in will return `true` which is incorrect because the latest review from `peter` is `Request changes`.

You can see a live example here https://github.com/reviewpad/schemas/pull/11

## How to reproduce

1. Define a reviewpad.yml with the following configuration (replace `peter` by your GitHub user):

```yml
api-version: reviewpad.com/v3.x

workflows:
  - name: hasRequiredApprovals
    if:
      - $hasRequiredApprovals(1, ["peter"])
    then:
      - $comment("hasRequiredApprovals is true")
```

2. Open a pull request with a user different from the one defined in the configuration
3. Approve the pull request. You will see the comment `hasRequiredApprovals is true`
4. Request changes. You will see the comment `hasRequiredApprovals is true`. This shouldn't be the case.

## Expected behavior

The built-in `hasRequiredApprovals` should look into the latest reviews.
