### ISSUE TITLE
removeLabel not working

### ISSUE THREAD

**Issue by marcelosousa** [reviewpad/reviewpad#819]
## Describe the bug

In the following workflow:

```
workflows:
  - name: add-remove-label
    on:
      - issue
    if:
      - rule: true
        extra-actions:
          - $addLabel("running-ai")
          - $removeLabel("running-ai")
```

Reviewpad will not remove the label.
