### ISSUE TITLE
bug: the `assignCodeAuthorReviewers` built-in assigns a reviewer even when there is already an approval

### ISSUE THREAD

**Issue by fmallet** [reviewpad/reviewpad#863]
## Describe the bug

The `assignCodeAuthorReviewers` built-in is not supposed to assign a Reviewer when there is already a reviewer or when the PR has already one approval. But the second case is not correctly handled and so a new reviewer is assigned even when there is one approval on the PR.

## How to reproduce

Install Reviewpad and activate the following workflow:
```yaml
  - name: reviewer-assignment
    description: Assign the most relevant reviewer to pull requests
    run:
      - if: $isDraft() == false
        then: $assignCodeAuthorReviewers()
```

Once the PR is not anymore in draft mode, the PR is automatically assign to a reviewer X. When reviewer X approves the PR, a new reviewer Y is assigned to the PR -> KO

Create a PR

## Expected behavior

Once the PR is not anymore in draft mode, the PR is automatically assign to a reviewer X. When reviewer X approves the PR, the PR is  not assigned anymore to any reviewer.
