### ISSUE TITLE
$fail() action

### ISSUE THREAD

**Issue by marcelosousa** [reviewpad/reviewpad#87]
**Is your feature request related to a problem? Please describe.**
At the moment, we have added a `ignore-errors` flags to the Reviewpad configuration. 

However, in certain cases, it might be highly beneficial for the user to specify that the action should actually fail.

For example:

```yml
workflows:
  - name: fail-on-certain-pull-requests
    description: Certain pull requests should be blocked by Reviewpad to prevent merges
    if: 
      - rule: pull-request-is-blocked
    then:
      - '$fail()'
```

**Describe the solution you'd like**
A new built-in action `$fail()` that simply returns an error so that the Reviewpad action is red.
