### ISSUE TITLE
Update state on actions

### ISSUE THREAD

**Issue by marcelosousa** [reviewpad/reviewpad#881]
## Description

Reviewpad engine runs in two stages:

1. Given a reviewpad.yml and an entity, synthesise an aladino program to be executed.
2. Execute the aladino program

The problem with this approach is that the program synthesis part uses the state of the entity at the beginning of the execution. 
For example:

```
workflows:
  - name: add-test-label
    run:
      - $addLabel("test")
  
  - name: add-follow-up-label
    run:
      - if: $isElementOf("test", $labels())
        then: $addLabel("follow-up")
```

Given a pull request that was just opened without the "test" label, the output aladino program will be `$addLabel("test")`. Then we rely on the fact that since adding a label will trigger again Reviewpad, in the second execution, it will output the program `$addLabel("test"); $addLabel("follow-up")`.

## Proposed solution

Fuse the two stages so that in one execution Reviewpad adds both labels.
