### ISSUE TITLE
Log reports a wrong warning message

### ISSUE THREAD

**Issue by ferreiratiago** [reviewpad/reviewpad#957]
## Describe the bug

Currently, when using an inline rule, a warning message is shown in the Reviewpad log saying that the rule is not being used.

## How to reproduce

Set the following Reviewpad configuration and trigger Reviewpad.
```yml
workflows:
  - name: For Test Purpose
    run:
      - if: true == true
        then: $failCheckStatus("failure 1")
```

You should see the following warning message:
<img width="409" alt="image" src="https://github.com/reviewpad/reviewpad/assets/3806676/6e3a847e-4cfb-44e9-ba15-366a4f7dc729">

## Expected behavior

The warning message should not appear when the rule is being used.
