### ISSUE TITLE
Update DSL to include checks

### ISSUE THREAD

**Issue by ferreiratiago** [reviewpad/reviewpad#971]
## Description

We are introducing the definition of checks and therefore we need to add it to the DSL.

The definition of checks is the following:
```yml
checks:
  CHECK-ID:
    parameters:
      PARAMETER1-ID: [STRING | BOOLEAN | INTEGER]
      ...
    severity: [LOW | HIGH | MEDIUM]
```

At the end of this issue, a user should be able to define a check into its reviewpad configuration.

It is not expected for the check to take any effect, meaning that the check's processing is not included in this issue.
