### ISSUE TITLE
Provide a `$dictionaryValueFromKey(dictionary, key)` built-in to get access to a dictionary value

### ISSUE THREAD

**Issue by fmallet** [reviewpad/reviewpad#998]
### WHY

Reviewpad supports [dictionaries](https://docs.reviewpad.com/guides/syntax#dictionary) and the ability to [iterate over those dictionaries](https://docs.reviewpad.com/guides/syntax#loop-over-a-dictionary) but we don't provide any solution to directly get access to one value of the dictionary by key.

The workaround to mimic this behavior is to iterate over all the elements of the dictionary and to trigger an action when the expected key is found:

```yaml
              forEach:
                key: $theKey
                value: $theValue
                in: $dictionary("theDictionary")
                do:
                  if: $theKey == $theExpectedKey
                  then: ... do something
```

### WHAT

We are introducing a new built-in named `$dictionaryValueFromKey`. This built-in accepts two parameters:
- `dictionary`: the dictionary from which the value will be retrieved.
- `key`: the key for the value we wish to fetch.

The returned value can vary in type, depending on the nature of the dictionary used. It could be either a string or an array.
